name: Test
on:
  push:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    # Update Python https://github.com/actions/setup-python
    - name: update python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: install poetry
      run: >
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        | python -

    - name: set env
      run: echo "PATH=${PATH}:$HOME/.poetry/bin" >> $GITHUB_ENV

    - name: checkout branch
      uses: actions/checkout@v2

    - name: install packages via poetry
      run: poetry install

    - name: check type annotation
      run: poetry run mypy

    - name: check lint
      run: poetry run pylint area_information_city
